# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net


# 1. Set the following secrets in your repository (instructions for getting these can be found at https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux):
#    - AZURE_CLIENT_ID
#    - AZURE_TENANT_ID
#    - AZURE_SUBSCRIPTION_ID

name: .NET


permissions:
      id-token: write
      contents: read

on:
  workflow_dispatch:
  #push:
    #branches: [ "master" ]
  #pull_request:
  #  types:
  #    - opened
  #  branches: [ "master" ]
  #pull_request_target:
  #  branches: [ "master" ]
  #  types:
  #    - closed
    
env:
  REGISTRY: goaaroregistry.azurecr.io
  APP: DLHAPI
  APP-IMAGE: dlh-api-test
  GIT_DEPLOY_REPO: dlh-api-test-manifests
  GH_TOKEN: ${{ github.token }}

  eOPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  eOPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "dlh-dev"
  HELM_RELEASE_NAME: dlh-api-test-runner
  

jobs:
  fetch:
    name: Code checkout
    #if: github.event_name == 'pull_request'
    #if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'dev')
 
    runs-on: ubuntu-latest
    #environment: 
    #  name: Dev
    steps:
      # Logs in with your Azure credentials
    - name: Azure login
      run: |
          az login --service-principal -u 024087d6-4aa7-4a52-90ec-0db8ffe1249e -p bQB8Q~e4xs-H6EwEMrJ-HEl7mtKVar-vKZAjAcL- --tenant 2bb51c06-af9b-42c5-8bf5-3c3b7b10850b
    - name: Azure keyvault list secret
      run: |
          az keyvault secret list --vault-name "onpremprod-dlh-dev"
